
时间：2017-05-24 08:47:10,223 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：55064156 
System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   在 System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   在 System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.App.DBDataContext.GetDictList(String code, String upval) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 93
   在 X.App.Apis.cate.list.tree_LoadList(Object id) 位置 D:\Pro\x.link\src\Web\X.App\Apis\cate\list.cs:行号 31
   在 X.App.XTree.getChild(TreeNode n, Int32 d) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 63
   在 X.App.XTree.InitTree(String title, Int32 deep) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 27
   在 X.App.Apis.cate.list.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\cate\list.cs:行号 20
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

时间：2017-05-24 08:47:10,223 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接)
   在 System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   在 System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   在 System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   在 System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   在 System.Data.SqlClient.SqlConnection.Open()
   在 System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)
   在 System.Data.Linq.SqlClient.SqlProvider.get_IsSqlCe()
   在 System.Data.Linq.SqlClient.SqlProvider.InitializeProviderMode()
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 X.App.DBDataContext.GetDictList(String code, String upval) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 93
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 75
   在 X.App.Views.cate.edit.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\cate\edit.cs:行号 24
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：55064156 

时间：2017-05-24 08:47:10,227 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：55064160 
System.Data.SqlClient.SqlException (0x80131904): 在与 SQL Server 建立连接时出现与网络相关的或特定于实例的错误。未找到或无法访问服务器。请验证实例名称是否正确并且 SQL Server 已配置为允许远程连接。 (provider: Named Pipes Provider, error: 40 - 无法打开到 SQL Server 的连接) ---> System.ComponentModel.Win32Exception (0x80004005): 找不到网络路径。
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20

时间：2017-05-24 09:26:54,300 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：索引超出了数组界限。
   在 NVelocity.Runtime.Parser.Node.SimpleNode.GetChild(Int32 i)
   在 NVelocity.Runtime.Directive.Foreach.Render(IInternalContextAdapter context, TextWriter writer, INode node)
   在 NVelocity.Runtime.Parser.Node.ASTDirective.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Parser.Node.ASTBlock.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Parser.Node.ASTIfStatement.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Parser.Node.ASTBlock.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Directive.Foreach.Render(IInternalContextAdapter context, TextWriter writer, INode node)
   在 NVelocity.Runtime.Parser.Node.ASTDirective.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Parser.Node.SimpleNode.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Template.Merge(IContext context, TextWriter writer)
   在 X.Web.Com.Tpl.Merge(String templatePath, IDictionary`2 dict) 位置 D:\Pro\x.link\src\X.Web\Com\Tpl.cs:行号 98
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 103 
时间：93881 

时间：2017-05-24 09:26:54,342 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：93923 
System.IndexOutOfRangeException: 索引超出了数组界限。
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 10:17:50,600 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：Encountered "in" at line 127, column 50.
Was expecting one of:
    <RPAREN> ...
    "-" ...
    "+" ...
    "*" ...
    "/" ...
    "%" ...
    "&&" ...
    "||" ...
    "<" ...
    "<=" ...
    ">" ...
    ">=" ...
    "==" ...
    "!=" ...
    "=" ...
    
   在 NVelocity.Template.Process()
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.LoadResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.GetResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.RuntimeInstance.GetTemplate(String name)
   在 NVelocity.App.Velocity.GetTemplate(String name)
   在 X.Web.Com.Tpl.Merge(String templatePath, IDictionary`2 dict) 位置 D:\Pro\x.link\src\X.Web\Com\Tpl.cs:行号 77
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 103 
时间：389 

时间：2017-05-24 10:17:50,689 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：479 
NVelocity.Exception.ParseErrorException: Encountered "in" at line 127, column 50.
Was expecting one of:
    <RPAREN> ...
    "-" ...
    "+" ...
    "*" ...
    "/" ...
    "%" ...
    "&&" ...
    "||" ...
    "<" ...
    "<=" ...
    ">" ...
    ">=" ...
    "==" ...
    "!=" ...
    "=" ...
     ---> NVelocity.Runtime.Parser.ParseException: Encountered "in" at line 127, column 50.
Was expecting one of:
    <RPAREN> ...
    "-" ...
    "+" ...
    "*" ...
    "/" ...
    "%" ...
    "&&" ...
    "||" ...
    "<" ...
    "<=" ...
    ">" ...
    ">=" ...
    "==" ...
    "!=" ...
    "=" ...
    
   在 NVelocity.Runtime.Parser.Parser.Parse(TextReader reader, String templateName)
   在 NVelocity.Runtime.RuntimeInstance.Parse(TextReader reader, String templateName, Boolean dumpNamespace)
   在 NVelocity.Runtime.RuntimeInstance.Parse(TextReader reader, String templateName)
   在 NVelocity.Template.Process()
   --- 内部异常堆栈跟踪的结尾 ---
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 15:28:36,172 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：4603 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.load.<>c__DisplayClass12_0.<Execute>b__0(x_dict o) 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   在 System.Linq.Enumerable.<OfTypeIterator>d__92`1.MoveNext()
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitContains(Expression sequence, Expression value)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitWhere(Expression sequence, LambdaExpression predicate)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitWhere(Expression sequence, LambdaExpression predicate)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitAggregate(Expression sequence, LambdaExpression lambda, SqlNodeType aggType, Type returnType)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.ConvertOuter(Expression node)
   在 System.Data.Linq.SqlClient.SqlProvider.BuildQuery(Expression query, SqlNodeAnnotations annotations)
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Linq.IQueryProvider.Execute[S](Expression expression)
   在 System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 34
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 15:29:42,922 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：229 
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 X.App.Apis.load.<>c__DisplayClass16_0.<Execute>b__0(x_dict o) 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 29
   在 System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   在 System.Linq.Enumerable.<OfTypeIterator>d__92`1.MoveNext()
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   在 System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitContains(Expression sequence, Expression value)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitExpression(Expression exp)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitWhere(Expression sequence, LambdaExpression predicate)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitAggregate(Expression sequence, LambdaExpression lambda, SqlNodeType aggType, Type returnType)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitSequenceOperatorCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitMethodCall(MethodCallExpression mc)
   在 System.Data.Linq.SqlClient.QueryConverter.VisitInner(Expression node)
   在 System.Data.Linq.SqlClient.QueryConverter.ConvertOuter(Expression node)
   在 System.Data.Linq.SqlClient.SqlProvider.BuildQuery(Expression query, SqlNodeAnnotations annotations)
   在 System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)
   在 System.Data.Linq.DataQuery`1.System.Linq.IQueryProvider.Execute[S](Expression expression)
   在 System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 33
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:43:39,843 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：Unable to find resource 'mgr/com/_head.html'
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.LoadResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.GetResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.RuntimeInstance.GetTemplate(String name, String encoding)
   在 NVelocity.Runtime.Directive.Parse.GetTemplate(String arg, String encoding, IInternalContextAdapter context)
   在 NVelocity.Runtime.Directive.Parse.Render(IInternalContextAdapter context, TextWriter writer, INode node)
   在 NVelocity.Runtime.Parser.Node.ASTDirective.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Parser.Node.SimpleNode.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Template.Merge(IContext context, TextWriter writer)
   在 X.Web.Com.Tpl.Merge(String templatePath, IDictionary`2 dict) 位置 D:\Pro\x.link\src\X.Web\Com\Tpl.cs:行号 98
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 103 
时间：337 

时间：2017-05-24 16:43:39,935 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：429 
NVelocity.Exception.ResourceNotFoundException: Unable to find resource 'mgr/com/_head.html'
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:45:01,301 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":" ","code":"0x0022"} 
时间：81795 

时间：2017-05-24 16:47:18,927 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 20
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：219421 

时间：2017-05-24 16:47:18,927 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":" ","code":"0x0006"} 
时间：219421 

时间：2017-05-24 16:47:44,590 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 20
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：201 

时间：2017-05-24 16:47:44,657 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":" ","code":"0x0006"} 
时间：268 

时间：2017-05-24 16:49:02,481 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 20
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：192 

时间：2017-05-24 16:49:02,733 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":" ","code":"0x0006"} 
时间：443 

时间：2017-05-24 16:50:12,022 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 20
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：198 

时间：2017-05-24 16:50:12,233 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：409 

时间：2017-05-24 16:50:22,673 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":" ","code":"0x0022"} 
时间：10849 

时间：2017-05-24 16:50:29,176 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":" ","code":"0x0022"} 
时间：17351 

时间：2017-05-24 16:51:19,375 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0006"} 
时间：246 

时间：2017-05-24 16:51:33,247 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0006"} 
时间：14118 

时间：2017-05-24 16:54:21,837 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0006"} 
时间：4240 

时间：2017-05-24 16:55:23,648 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户名或密码不正确 ","code":"0x0007"} 
时间：8922 

时间：2017-05-24 16:55:26,725 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"验证码不正确 ","code":"0x0006"} 
时间：12000 

时间：2017-05-24 16:55:35,111 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：20386 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:55:36,674 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：21949 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:55:38,372 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：23647 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:55:46,380 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：31655 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:55:49,479 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：34754 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:56:00,267 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：45542 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:56:00,930 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：46204 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:56:01,433 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：46707 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:56:01,921 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：47196 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:56:08,577 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：53851 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:56:33,337 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：6531 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:56:34,261 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：7455 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:56:35,421 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：8615 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:57:08,390 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：41584 
System.ArgumentException: 参数无效。
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   在 System.Drawing.Bitmap..ctor(Int32 width, Int32 height)
   在 X.Web.Views.Code.CreateImage(String randomcode) 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 46
   在 X.Web.Views.Code.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\Code.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:57:57,243 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 20
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：14692 

时间：2017-05-24 16:57:57,332 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：14781 

时间：2017-05-24 16:58:25,695 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 20
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：43144 

时间：2017-05-24 16:58:25,704 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：43153 

时间：2017-05-24 16:58:41,798 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：Unable to find resource 'mgr/com/_head.html'
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.LoadResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.GetResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.RuntimeInstance.GetTemplate(String name, String encoding)
   在 NVelocity.Runtime.Directive.Parse.GetTemplate(String arg, String encoding, IInternalContextAdapter context)
   在 NVelocity.Runtime.Directive.Parse.Render(IInternalContextAdapter context, TextWriter writer, INode node)
   在 NVelocity.Runtime.Parser.Node.ASTDirective.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Parser.Node.SimpleNode.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Template.Merge(IContext context, TextWriter writer)
   在 X.Web.Com.Tpl.Merge(String templatePath, IDictionary`2 dict) 位置 D:\Pro\x.link\src\X.Web\Com\Tpl.cs:行号 98
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 103 
时间：59247 

时间：2017-05-24 16:58:41,838 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：59287 
NVelocity.Exception.ResourceNotFoundException: Unable to find resource 'mgr/com/_head.html'
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 16:59:14,679 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：Unable to find resource 'mgr/com/_head.html'
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.LoadResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.GetResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.RuntimeInstance.GetTemplate(String name, String encoding)
   在 NVelocity.Runtime.Directive.Parse.GetTemplate(String arg, String encoding, IInternalContextAdapter context)
   在 NVelocity.Runtime.Directive.Parse.Render(IInternalContextAdapter context, TextWriter writer, INode node)
   在 NVelocity.Runtime.Parser.Node.ASTDirective.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Parser.Node.SimpleNode.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Template.Merge(IContext context, TextWriter writer)
   在 X.Web.Com.Tpl.Merge(String templatePath, IDictionary`2 dict) 位置 D:\Pro\x.link\src\X.Web\Com\Tpl.cs:行号 98
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 103 
时间：92128 

时间：2017-05-24 16:59:14,702 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：92151 
NVelocity.Exception.ResourceNotFoundException: Unable to find resource 'mgr/com/_head.html'
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:03:38,700 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：330 

时间：2017-05-24 17:03:39,101 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：731 

时间：2017-05-24 17:06:04,185 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：214 

时间：2017-05-24 17:06:04,390 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：418 

时间：2017-05-24 17:06:20,225 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"接口不存在 cate.list","code":"0x0002"} 
时间：16253 

时间：2017-05-24 17:10:44,430 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：201 

时间：2017-05-24 17:10:44,637 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：408 

时间：2017-05-24 17:14:19,265 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：228 

时间：2017-05-24 17:14:19,480 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：443 

时间：2017-05-24 17:14:38,783 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：19746 

时间：2017-05-24 17:14:38,785 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：19748 

时间：2017-05-24 17:15:18,344 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：值不能为 null。
参数名: source
   在 System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.Views.com.dict.tree_LoadList(Object id) 位置 D:\Pro\x.link\src\Web\X.App\Views\com\dict.cs:行号 52
   在 X.App.XTree.getChild(TreeNode n, Int32 d) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 63
   在 X.App.XTree.InitTree(String title, Int32 deep) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 27
   在 X.App.Views.com.dict.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\com\dict.cs:行号 40
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：59307 

时间：2017-05-24 17:15:18,357 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：59320 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:15:43,629 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：值不能为 null。
参数名: source
   在 System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.Views.com.dict.tree_LoadList(Object id) 位置 D:\Pro\x.link\src\Web\X.App\Views\com\dict.cs:行号 52
   在 X.App.XTree.getChild(TreeNode n, Int32 d) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 63
   在 X.App.XTree.InitTree(String title, Int32 deep) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 27
   在 X.App.Views.com.dict.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\com\dict.cs:行号 40
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：84592 

时间：2017-05-24 17:15:43,630 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：84593 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:15:56,526 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：值不能为 null。
参数名: source
   在 System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.Views.com.dict.tree_LoadList(Object id) 位置 D:\Pro\x.link\src\Web\X.App\Views\com\dict.cs:行号 52
   在 X.App.XTree.getChild(TreeNode n, Int32 d) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 63
   在 X.App.XTree.InitTree(String title, Int32 deep) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 27
   在 X.App.Views.com.dict.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\com\dict.cs:行号 40
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：242 

时间：2017-05-24 17:15:56,612 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：328 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:15:59,563 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：值不能为 null。
参数名: source
   在 System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.Views.com.dict.tree_LoadList(Object id) 位置 D:\Pro\x.link\src\Web\X.App\Views\com\dict.cs:行号 52
   在 X.App.XTree.getChild(TreeNode n, Int32 d) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 63
   在 X.App.XTree.InitTree(String title, Int32 deep) 位置 D:\Pro\x.link\src\Web\X.App\Com\XTree.cs:行号 27
   在 X.App.Views.com.dict.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\com\dict.cs:行号 40
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：3279 

时间：2017-05-24 17:15:59,565 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：3281 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 112
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:16:01,602 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：5319 

时间：2017-05-24 17:16:01,741 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：5457 

时间：2017-05-24 17:16:53,930 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：195 

时间：2017-05-24 17:16:54,133 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：398 

时间：2017-05-24 17:20:22,898 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：2484 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:20:25,079 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：4665 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:20:25,524 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：5111 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:20:26,054 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：5641 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:20:26,697 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：6283 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:20:47,063 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：26649 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:20:48,783 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：28370 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:20:49,260 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：28846 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:20:49,759 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：29345 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:22:02,523 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：2966 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:22:32,430 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：2772 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:23:09,488 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：21911 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:23:53,591 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：66013 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   在 X.App.DBDataContext.GetDict(String code, String val) 位置 D:\Pro\x.link\src\Web\X.App\Com\DB.cs:行号 76
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 28
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:24:10,468 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(:0) - 
错误：致命错误 
时间：82891 
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   在 X.App.Apis.load.Execute() 位置 D:\Pro\x.link\src\Web\X.App\Apis\load.cs:行号 35
   在 X.Web.Apis.Api.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Apis\Api.cs:行号 30
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\x.link\src\X.Web\XApp.cs:行号 31

时间：2017-05-24 17:31:53,333 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：Unable to find resource 'com/_head.html'
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.LoadResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.GetResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.RuntimeInstance.GetTemplate(String name, String encoding)
   在 NVelocity.Runtime.Directive.Parse.GetTemplate(String arg, String encoding, IInternalContextAdapter context)
   在 NVelocity.Runtime.Directive.Parse.Render(IInternalContextAdapter context, TextWriter writer, INode node)
   在 NVelocity.Runtime.Parser.Node.ASTDirective.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Parser.Node.SimpleNode.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Template.Merge(IContext context, TextWriter writer)
   在 X.Web.Com.Tpl.Merge(String templatePath, IDictionary`2 dict) 位置 D:\Pro\x.link\src\X.Web\Com\Tpl.cs:行号 98
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 103 
时间：22320 

时间：2017-05-24 17:32:06,991 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：35978 

时间：2017-05-24 17:32:06,994 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：Unable to find resource 'com/_head.html'
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.LoadResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.Resource.ResourceManagerImpl.GetResource(String resourceName, ResourceType resourceType, String encoding)
   在 NVelocity.Runtime.RuntimeInstance.GetTemplate(String name, String encoding)
   在 NVelocity.Runtime.Directive.Parse.GetTemplate(String arg, String encoding, IInternalContextAdapter context)
   在 NVelocity.Runtime.Directive.Parse.Render(IInternalContextAdapter context, TextWriter writer, INode node)
   在 NVelocity.Runtime.Parser.Node.ASTDirective.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Runtime.Parser.Node.SimpleNode.Render(IInternalContextAdapter context, TextWriter writer)
   在 NVelocity.Template.Merge(IContext context, TextWriter writer)
   在 X.Web.Com.Tpl.Merge(String templatePath, IDictionary`2 dict) 位置 D:\Pro\x.link\src\X.Web\Com\Tpl.cs:行号 98
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 103 
时间：35981 

时间：2017-05-24 17:32:32,153 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：引发类型为“X.Web.XExcep”的异常。
   在 X.App.Views.mgr.xmg.InitDict() 位置 D:\Pro\x.link\src\Web\X.App\Views\mgr\xmg.cs:行号 23
   在 X.Web.Views.View.GetResponse() 位置 D:\Pro\x.link\src\X.Web\Views\View.cs:行号 102 
时间：61139 

时间：2017-05-24 17:32:32,251 
级别：ERROR 
出错类：Error property: [(null)] 
出错位置：X.Core.Plugin.Loger.Error(:0) - 
错误：{"issucc":false,"msg":"用户登陆超时 ","code":"0x0005"} 
时间：61238 
